steps:

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build',
           '--tag', '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REGISTRY}/${_PKG}/${_STAGE}/app:${_VERSION}',
           '--build-arg', 'STAGE=${_STAGE}',
           '--file', 'Dockerfile', '.']
    id: 'build: core'


  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REGISTRY}/${_PKG}/${_STAGE}/app:${_VERSION}']
    id: 'push: app'

  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
        'run',
        'deploy',
        '${_PKG}-api',
        '--image=${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REGISTRY}/${_PKG}/${_STAGE}/app:${_VERSION}',
        '--region', '${_REGION}',
        '--allow-unauthenticated',
        '--min-instances', '0',
        '--max-instances', '5'

    ]
    id: 'deploy: app'
    waitFor: ['push: app']

timeout: 3600s

substitutions:
  _PROJECT_ID: asr-2023-p6
  _REGION: 'europe-west1'
  _PKG: prototype
  _REGISTRY: p7
  _VERSION: 0.0.1
  
  
  
  
